### ISSUE TITLE
Quick way to reload file

### ISSUE THREAD

**Issue by sammko** [solemnwarning/rehex#124] opened 2021-04-30 17:41 UTC
I don't see a way to quickly reload the contents of a file, other than opening it anew, which loses the viewport position. A reload function (mapped to F5 or Ctrl+R for example) would be useful.

Maybe also an opt-in autoreload feature, which would detect changes (inotify etc) and reload the file? Or maybe prompt for a reload?

Thanks for this tool by the way, I've always missed a good non-bloated hex editor.

**Comment by solemnwarning** [comment] 2021-05-01 09:32
I hadn't gotten round to dealing with the file changing under the editor yet as it's a bit awkward - the file isn't actually loaded into memory whole by design*; blocks get paged in and out as necessary - in effect it's kind of reloading the file continuously, except blocks which have been modified.

There are things I could do here - lock the whole file in memory if it's small enough, or warn if the file is changed on disk and refuse to page in unloaded blocks after an external change. Any ideas welcome :)

**Comment by solemnwarning** [comment] 2023-05-15 22:13
Merged in 955ad367fb65bab555d5d35bc66b57e1e178d06a.

**Closed by solemnwarning** 2023-05-15 22:13 UTC
Labels: feature
